DhavalSir_TASK/DhavalSir_TASK/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DhavalSir_TASK.Models;
namespace DhavalSir_TASK.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        ProductsDataContext objcust = new ProductsDataContext();
        public ActionResult Index()
        {
            var c1 = from c in objcust.CustomerTBs select c;
            return View(c1);
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            var c2 = from c in objcust.CustomerTBs where c.CustomerId == id select c;
            return View(c2.First());
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(CustomerTB cust)
        {
            try
            {
                objcust.CustomerTBs.InsertOnSubmit(cust);
                objcust.SubmitChanges();
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int id)
        {
            var c2 = from c in objcust.CustomerTBs where c.CustomerId == id select c;
            return View(c2.First());
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id,CustomerTB cust)
        {
            try
            {
                var c2 = from c in objcust.CustomerTBs where c.CustomerId ==id select c;
                c2.First().CustomerName = cust.CustomerName;
                c2.First().Age = cust.Age;
                c2.First().Email = cust.Email;
                c2.First().Gender = cust.Gender;
                objcust.SubmitChanges();
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int id)
        {
            var c3 = from c in objcust.CustomerTBs where c.CustomerId == id select c;
            objcust.CustomerTBs.DeleteOnSubmit(c3.First());
            objcust.SubmitChanges();
            return RedirectToAction("Index");
        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DhavalSir_TASK/DhavalSir_TASK/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DhavalSir_TASK.Models;
namespace DhavalSir_TASK.Controllers
{
    
    public class ProductController : Controller
    {
        ProductsDataContext objProduct = new ProductsDataContext();

        // GET: Product
        public ActionResult Index()
        {
            
            return View(objProduct.ProductsTBs.ToList());
        }
        [HttpPost]
        public ActionResult Index(string name)
        {
            var q = from x in objProduct.ProductsTBs where x.ProductName.Contains(name) select x;

            return View(q.ToList());
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            var s1 = objProduct.ProductsTBs.SingleOrDefault(s => s.ProductId == id);
            return View(s1);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(ProductsTB NewProduct)
        {
            try
            {
                // TODO: Add insert logic here
                objProduct.ProductsTBs.InsertOnSubmit(NewProduct);
                objProduct.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            var s1 = objProduct.ProductsTBs.SingleOrDefault(s => s.ProductId == id);
            return View(s1);
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ProductsTB NewProduct)
        {
            try
            {
                var s1 = objProduct.ProductsTBs.SingleOrDefault(s2 => s2.ProductId == id);
                s1.ProductName = NewProduct.ProductName;
                s1.Price = NewProduct.Price;
                s1.Quantity = NewProduct.Quantity;
                s1.Description = NewProduct.Description;
                objProduct.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            var s1 = objProduct.ProductsTBs.SingleOrDefault(s => s.ProductId == id);
            objProduct.ProductsTBs.DeleteOnSubmit(s1);
            objProduct.SubmitChanges();
            return RedirectToAction("index");
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult SearchProduct()
        {
            return View();
        }
    }
}

DhavalSir_TASK/DhavalSir_TASK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                    <li>@Html.ActionLink("Products", "index", "Product")</li>
                    <li>@Html.ActionLink("Customers", "index", "Customer")</li>
                    <li>@Html.ActionLink("Orders", "index", "Orders")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>